language: python
python:
- '3.6'
cache:
  directories:
  - ".cache"
os:
- linux
install:
- source scripts/bootstrap
- conda build conda_recipe
- conda install abeona --use-local
script:
- conda list
- make test
