language: python
python:
- '3.6'
cache:
  directories:
  - ".cache"
os:
- linux
install:
- scripts/bootstrap
script:
- source activate test-environment && conda list
- source activate test-environment && make test
