name: test-environment
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.6
  - mccortex >=1.0
  - nextflow >=0.31.1
  - kallisto >=0.44.0
  - sphinx
  - twine
  - wheel
  - pytest-benchmark
  - coverage>=4.5
  - tox
  - bumpversion
