name: test-environment
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.6
  - conda-build
  - bwa
  - kallisto>=0.44.0
  - mccortex>=1.0
  - nextflow=19.01.0
  - samtools
  - seqtk
  - tox
