name: test-environment
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.6
  - mccortex
  - nextflow
  - sphinx
  - twine
  - wheel
  - pytest-benchmark
  - coverage>=4.5
  - tox
  - bumpversion
