#!/usr/bin/env bash
# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'

scripts/bootstrap

python setup.py install

MCCORTEX=${MCCORTEX:-'mccortex'}
KMER_SIZE=${KMER_SIZE:-'47'}
FIXTURE_DIR=fixtures/yeast

$MCCORTEX $KMER_SIZE build --force --sort --memory 2G -k $KMER_SIZE --sample yeast.chrom \
    --seq $FIXTURE_DIR/NC_001133.9.fa \
    $FIXTURE_DIR/NC_001133.9.ctx

for SIZE in 1 2 4 8; do
    awk "{print substr(\$0, 1, $SIZE * 1000)}" < $FIXTURE_DIR/NC_001133.9.fa > $FIXTURE_DIR/NC_001133.9.${SIZE}kbp.fa
$MCCORTEX $KMER_SIZE build --force --sort --memory 2G -k 47 --sample yeast.chrom \
    --quiet \
    --seq $FIXTURE_DIR/NC_001133.9.${SIZE}kbp.fa \
    $FIXTURE_DIR/NC_001133.9.${SIZE}kbp.ctx
done
